services:
  ### create_service_inject
  inject:
    image: ((docker-app_inject-repository)):((docker-app_inject-tag))((docker-additional-tag))
    environment:
      - DEPENDS_ON=${NATS_NAME}
      - GATLING_TO_NATS_SUBJECT=${GATLING_TO_NATS_SUBJECT}
      - NATS_NAME=${NATS_NAME}
      - GATLING_USERS_PER_SEC=${GATLING_USERS_PER_SEC}
      - GATLING_DURATION=${GATLING_DURATION}
      - STREAMING_DURATION=${STREAMING_DURATION}
      - RANDOMNESS=${VOLTAGE_RANDOMNESS}
      - PREDICTION_LENGTH=${PREDICTION_LENGTH}
      - TIME_ROOT=${TIME_ROOT}
    command: --no-reports -s ${GATLING_MAIN_CLASS}
