services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - locust-kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - locust-kafka-network

  locust:
    build:
      context: .
      dockerfile: ./locust/Dockerfile
    depends_on:
      - kafka
    networks:
      - locust-kafka-network
    ports:
      - "8089:8089"
    command: ["locust", "-f", "smart_meter_locustfile.py"]

networks:
  locust-kafka-network:
    driver: bridge
