services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    command: ["/opt/bitnami/scripts/spark/entrypoint.sh", "/opt/bitnami/scripts/spark/run.sh"]
    volumes:
      - spark-volume:/opt/bitnami/spark

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ["/opt/bitnami/scripts/spark/entrypoint.sh", "/opt/bitnami/scripts/spark/run.sh"]
    volumes:
      - spark-volume:/opt/bitnami/spark

  spark_app1:
    build: .
    container_name: spark_app1
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HADOOP_HOME=/opt/bitnami/hadoop
      - JAVA_HOME=/opt/bitnami/java
      - HOME=/root
    depends_on:
      - spark-master
    ports:
      - "4040:4040"

volumes:
  spark-volume:
