services:
  ### create_service_prediction_trainer,
  app_prediction_trainer:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}

  ### create_service_prediction_oracle,
  app_prediction_oracle:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
