services:
  ### ["create_service_telegraf_on_master", "prediction"],
  telegraf_prediction:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
